name: close_checker
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  go_router: ^4.2.7
  logger: ^1.1.0
  intl: ^0.17.0
  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.4
  uuid: ^3.0.6
  flutter_slidable: ^2.0.0
  sqflite: ^2.0.3+1
  path: ^1.8.1
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  firebase_storage: ^10.3.9
  flutter_hooks: ^0.18.5+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.2.0
  json_serializable: ^6.3.1
  json_annotation: 4.6.0

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
   - family: RocknRoll_One
     fonts:
       - asset: assets/font/RocknRoll_One/RocknRollOne-Regular.ttf
   - family: Yusei_Magic
     fonts:
       - asset: assets/font/Yusei_Magic/YuseiMagic-Regular.ttf


       