name: close_checker
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  go_router: ^4.2.7
  build_runner: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
  assets:
    - assets/